### ISSUE TITLE
Show keyword in context for multiple keyword searches

### ISSUE THREAD

**Issue by rosanna-smith** [Language-Research-Technology/oni-ui#11]
In cases where the two (or more) keywords don't appear right next to each other, it would be helpful if multiple highlighted samples appeared. Eg. in advanced search using (high AND country), two of the results only show one of the words:
![image](https://github.com/Language-Research-Technology/oni-ui/assets/143474414/695a6453-a124-42c2-af5b-6425ffef3e24)

**Comment by rosanna-smith** [comment]
Further to this one, using 'corpus' as a basic search keyword:

- The results where the keyword also appears in the title, none of the keywords are highlighted in either the title or KWIC text. The only ones that are highlighted are results further down where the keyword only appears in the KWIC text.
- If the keyword appears only in the description, that isn't highlighted either.

**Comment by rosanna-smith** [comment]
Is it possible to have multiple highlight phrases?

**Comment by moisbo** [comment]
I'm closing this because:
- We cannot highlight other than TEXT fields so other things will not be highlighted like description, name, etc.
- We cannot highlight multiple phrases because the size of the fragment is limited to not show all the text. (people can do multiple searches)
- If you have 2 words and dont appear close to the fragment size it will not show because it exceeds the size of the fragment.

People can still do api searches with the actual thing they want, for example changing the query `/search` to do what they need. Or can use a notebook if they want a very explicit search
