### ISSUE TITLE
Arabic script languages have PDF characters in txt version

### ISSUE THREAD

**Issue by rosanna-smith** [Language-Research-Technology/oni-ui#18]
Arabic and Persian/Iranian txt files adapted from the pdfs have this character throughout the documents:
‬	202c	61	POP DIRECTIONAL FORMATTING
Is that expected for the txt versions?
![Screenshot 2023-09-14 at 3 15 09 pm](https://github.com/Language-Research-Technology/oni-ui/assets/143474414/944fefff-4095-452c-a56a-79d3ca027fa8)

**Comment by smusgrav** [comment]
I remember that this came up before. It is something to do with the the export from pdf and my memory is that River figured out what it was /how to deal with it. I'll ask him.

**Comment by r-tae** [comment]
The Pop Directional Formatting characters are necessary/valid Unicode, I don't see any reason to get rid of them unless we're also transliterating the Arabic text. Their purpose is to end the most recent text direction.

They were causing a bug with the search, because they messed with the search index tokenisation. I think this is a bug with the tokeniser, because we should be able to handle text with a variety of invisible control characters. We wouldn't want our tokeniser to stumble over a ZWJ or a braille space either, but removing them changes the text.
