### ISSUE TITLE
Text spreads too much to right

### ISSUE THREAD

**Issue by smusgrav** [Language-Research-Technology/oni-ui#35]
Maria - provide screenshot please

**Comment by weaver-m** [comment]
![2023-10-27_dataPortal-onWideScreen](https://github.com/Language-Research-Technology/oni-ui/assets/60904846/ab5cafba-6d2e-4724-89d7-d9bc9bc9018f)
![2023-10-27_dataPortal_WideScreen_SearchHelpBtn](https://github.com/Language-Research-Technology/oni-ui/assets/60904846/2deccbfc-04d7-47de-b8ce-e4343de6f928)
2 screenshots here; 2nd one shows Advanced Search open and the Search Help button at top far right corner

**Comment by moisbo** [comment]
Hi @weaver-m what should we reduce? the search box? or the text in the right?

**Comment by moisbo** [comment]
Have a look @weaver-m @rosanna-smith. We can still adjust more if you like. Feel free to close it when you like

**Comment by rosanna-smith** [comment]
Seems to work ok on my screen, but over to Maria because it affected her view more.
This might be a separate issue (I can put one in if it is) - is there any way of reducing the number of vertical scroll bars, particularly the two on the right-hand side of the main page? Scrolling right to the end of the page or the collections can be tricky because you have to move the cursor to both sections. Eg. scrolling in the middle section doesn't get down to the pagination, so users might not realise it's there:
![Screenshot 2023-11-10 at 9 15 10 am](https://github.com/Language-Research-Technology/oni-ui/assets/143474414/5d76d4ee-3e07-4eaa-b313-f8c43340f5f8)
![Screenshot 2023-11-10 at 9 15 32 am](https://github.com/Language-Research-Technology/oni-ui/assets/143474414/0c3cbc3f-821a-4946-a182-bd9631484dcb)

**Comment by moisbo** [comment]
thats the browsers scroll bar... I actually dont see them and only see them when I scroll :D ... So its up to you to disable them or enable them. They come disabled in mac by default now.

<img width="1603" alt="Screenshot 2023-11-10 at 9 22 53 am" src="https://github.com/Language-Research-Technology/oni-ui/assets/2850269/1b8227fb-7136-404b-bbce-8db34634ac8e">

<img width="827" alt="Screenshot 2023-11-10 at 9 25 03 am" src="https://github.com/Language-Research-Technology/oni-ui/assets/2850269/04c33b09-3cc1-4ad1-83ec-d0c6adae3a76">

**Comment by rosanna-smith** [comment]
Weird, I've got the same settings as you but I still see the scrollbars. Just tested it out on Safari and it's the same as Firefox - using trackpad I can scroll right to the end without having to move the cursor to another area, but not if I use a mouse scroll wheel. I'm thinking more like the CLARIN website where it just has a single scroll rather than two (or three).

**Comment by moisbo** [comment]
That was something that was actually requested because they were saying there was too much scrolling

**Comment by weaver-m** [comment]
It looks better and the white space appears more balanced on the 27-inch monitor 

![Homepage-wide-screen](https://github.com/Language-Research-Technology/oni-ui/assets/60904846/06119dae-a58e-46ba-8fb6-0f33de0bf4bb)

![SearchResults-wideScreen](https://github.com/Language-Research-Technology/oni-ui/assets/60904846/71b9731a-edb8-440d-bedd-69254a540bc6)

**Comment by weaver-m** [comment]
I like that the header aligns with the body of the webpage

**Comment by weaver-m** [comment]
The footer height seems to be taller and takes up lot of space on the smaller screen [Macbook] especially as font sizes of texts are a bit chunky (should this be on a different ticket?) 

<img width="1436" alt="PageBottomFooter-Macbook" src="https://github.com/Language-Research-Technology/oni-ui/assets/60904846/1d819932-2260-42b9-a424-0fecc0dbbdff">

**Comment by moisbo** [comment]
reduced a little bit but not 50%
