### ISSUE TITLE
On the demo.ldaca page, noticed some cases where the languages aren't in the correct places on the map. This entry appears on the main page map in Sweden (could be fine for Finnish) but not in the UK for Welsh, even though this is listed as one of the countries. This Japanese entry also appears in Sweden.

### ISSUE THREAD

**Issue by moisbo** [Language-Research-Technology/oni-ui#80]
Try to do an analisis on the data to see if whether the data is wrong or not. And report it to Paradisec.

**Comment by rosanna-smith** [comment]
Checking this example in particular further:
https://demo.ldaca.edu.au/object?id=https%3A%2F%2Fcatalog.paradisec.org.au%2Frepository%2FAC1%2F303&_crateId=https%3A%2F%2Fcatalog.paradisec.org.au%2Frepository%2FAC1%2F303
The object's country is listed as Japan even though the map displays Sweden. Maybe this is because the overall [collection](https://demo.ldaca.edu.au/collection?id=https%3A%2F%2Fcatalog.paradisec.org.au%2Frepository%2FAC1&_crateId=https%3A%2F%2Fcatalog.paradisec.org.au%2Frepository%2FAC1) lists Sweden as one of many countries and it's pulling the location from there instead of the specific object?

**Comment by moisbo** [comment]
this is what the data has. Note at the polygon and if that is incorrect there isn't much we can do. But report it to Paradisec

**Comment by rosanna-smith** [comment]
Same as their page on PARADISEC, haven't contacted them now.
